Adding the second part of Chapter 4 (regression) for cohort #1
r4ds/bookclub-ps4ds pull request #9
Opened 2021-07-12 17:05 UTC by A-Farina

This PR provides the slides/notes from Cohort 1's discussion for chapter 4 part 2 (12 July 2021).

2021-07-16 15:40 UTC, jonthegeek requested changes
I recommend running a Build on the book to make sure it renders properly!

2021-07-16 15:40 UTC, jonthegeek commented on 04.Rmd
> +        neighborhoodgroup = as_factor(ntile(cum_cnt, 5)))
This line fails to render. It needs the `forcats::` prefix.
(there might be other errors after this one, but this kills the build)

2021-07-19 13:22 UTC, A-Farina commented on 04.Rmd
> +        neighborhoodgroup = as_factor(ntile(cum_cnt, 5)))
Thank you, I made that adjustment and built the book. It should work correctly now

2021-07-19 13:43 UTC, jonthegeek approved these changes
Looks good! Github Actions is making sure the book builds, if it does I'll merge this!

2021-07-19 13:54 UTC, merged